run:
	flutter run

clean:
	flutter clean

build-apk:
	flutter build apk

lint:
	flutter analyze

format:
	dart format lib/main.dart lib/pages/* lib/api_methods.dart

icons:
	flutter pub run flutter_launcher_icons:main
